// Code generated by hertz generator.

package main

import (
	"log"

	"github.com/ClubWeGo/douyin/kitex_server"
	"github.com/cloudwego/hertz/pkg/app/server"
	etcd "github.com/kitex-contrib/registry-etcd"
)

func main() {
	r, err := etcd.NewEtcdResolver([]string{"0.0.0.0:2379"})
	if err != nil {
		log.Fatal(err)
	}

	kitex_server.InitMicroServer(r)

	h := server.Default(server.WithMaxRequestBodySize(100 * 1024 * 1024))

	register(h)
	h.Spin()
}
