// Code generated by hertz generator.

package relation

import (
	"context"

	relation "github.com/ClubWeGo/douyin/biz/model/relation"
	"github.com/ClubWeGo/douyin/kitex_server"
	"github.com/ClubWeGo/douyin/tools"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// MessageChatMethod .
// @router /douyin/message/chat/ [POST]
func MessageChatMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.MessageChatReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(relation.MessageChatResp)

	ifvalid, userId, err := tools.ValidateToken(req.Token)
	if err != nil {
		msgFailed := "非法token"
		resp.StatusCode = 1
		resp.StatusMsg = &msgFailed
		c.JSON(consts.StatusOK, resp)
		return
	}
	if !ifvalid {
		msgFailed := "token无效"
		resp.StatusCode = 1
		resp.StatusMsg = &msgFailed
		c.JSON(consts.StatusOK, resp)
		return
	}

	messageList, err := kitex_server.GetAllMsg(userId, req.ToUserID)
	if err != nil {
		msgFailed := "获取消息失败"
		resp.StatusCode = 1
		resp.StatusMsg = &msgFailed
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.MessageList = messageList

	c.JSON(consts.StatusOK, resp)
}
