// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videoservice

import (
	"context"
	videomicro "github.com/ClubWeGo/videomicro/kitex_gen/videomicro"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateVideoMethod(ctx context.Context, request *videomicro.CreateVideoReq, callOptions ...callopt.Option) (r *videomicro.CreateVideoResp, err error)
	GetVideoAuthorIdMethod(ctx context.Context, request *videomicro.GetVideoAuthorIdReq, callOptions ...callopt.Option) (r *videomicro.GetVideoAuthorIdResp, err error)
	GetVideosByAuthorIdMethod(ctx context.Context, request *videomicro.GetVideosByAuthorIdReq, callOptions ...callopt.Option) (r *videomicro.GetVideosByAuthorIdResp, err error)
	GetVideoSetByIdSetMethod(ctx context.Context, request *videomicro.GetVideoSetByIdSetReq, callOptions ...callopt.Option) (r *videomicro.GetVideoSetByIdSetResp, err error)
	GetVideosFeedMethod(ctx context.Context, request *videomicro.GetVideosFeedReq, callOptions ...callopt.Option) (r *videomicro.GetVideosFeedResp, err error)
	UpdateVideoMethod(ctx context.Context, request *videomicro.UpdateVideoReq, callOptions ...callopt.Option) (r *videomicro.UpdateVideoResp, err error)
	DeleteVideoMethod(ctx context.Context, request *videomicro.DeleteVideoReq, callOptions ...callopt.Option) (r *videomicro.DeleteVideoResp, err error)
	GetUserVideoCountMethod(ctx context.Context, request *videomicro.GetUserVideoCountReq, callOptions ...callopt.Option) (r *videomicro.GetUserVideoCountResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoServiceClient struct {
	*kClient
}

func (p *kVideoServiceClient) CreateVideoMethod(ctx context.Context, request *videomicro.CreateVideoReq, callOptions ...callopt.Option) (r *videomicro.CreateVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateVideoMethod(ctx, request)
}

func (p *kVideoServiceClient) GetVideoAuthorIdMethod(ctx context.Context, request *videomicro.GetVideoAuthorIdReq, callOptions ...callopt.Option) (r *videomicro.GetVideoAuthorIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoAuthorIdMethod(ctx, request)
}

func (p *kVideoServiceClient) GetVideosByAuthorIdMethod(ctx context.Context, request *videomicro.GetVideosByAuthorIdReq, callOptions ...callopt.Option) (r *videomicro.GetVideosByAuthorIdResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideosByAuthorIdMethod(ctx, request)
}

func (p *kVideoServiceClient) GetVideoSetByIdSetMethod(ctx context.Context, request *videomicro.GetVideoSetByIdSetReq, callOptions ...callopt.Option) (r *videomicro.GetVideoSetByIdSetResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideoSetByIdSetMethod(ctx, request)
}

func (p *kVideoServiceClient) GetVideosFeedMethod(ctx context.Context, request *videomicro.GetVideosFeedReq, callOptions ...callopt.Option) (r *videomicro.GetVideosFeedResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetVideosFeedMethod(ctx, request)
}

func (p *kVideoServiceClient) UpdateVideoMethod(ctx context.Context, request *videomicro.UpdateVideoReq, callOptions ...callopt.Option) (r *videomicro.UpdateVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateVideoMethod(ctx, request)
}

func (p *kVideoServiceClient) DeleteVideoMethod(ctx context.Context, request *videomicro.DeleteVideoReq, callOptions ...callopt.Option) (r *videomicro.DeleteVideoResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteVideoMethod(ctx, request)
}

func (p *kVideoServiceClient) GetUserVideoCountMethod(ctx context.Context, request *videomicro.GetUserVideoCountReq, callOptions ...callopt.Option) (r *videomicro.GetUserVideoCountResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetUserVideoCountMethod(ctx, request)
}
