// Code generated by hertz generator.

package core

import (
	"context"

	core "github.com/ClubWeGo/douyin/biz/model/core"
	"github.com/ClubWeGo/douyin/kitex_server"
	"github.com/ClubWeGo/douyin/tools"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// LoginMethod .
// @router /douyin/user/login/ [POST]
func LoginMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	msgsucceed := "登录成功"
	msgFailed := "登录失败"

	resp := new(core.LoginResp)

	userid, err := kitex_server.LoginUser(req.Username, req.Password)
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMsg = &msgFailed
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.StatusMsg = &msgsucceed
	resp.UserID = userid
	resp.Token = tools.GenerateToken(userid)

	c.JSON(consts.StatusOK, resp)
}
