// Code generated by hertz generator.

package core

import (
	"context"

	core "github.com/ClubWeGo/douyin/biz/model/core"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishActionMethod .
// @router /douyin/publish/action/ [POST]
func PublishActionMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core.PublishActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(core.PublishActionResp)

	c.JSON(consts.StatusOK, resp)
}
