// Code generated by hertz generator.

package core

import (
	"context"

	core "github.com/ClubWeGo/douyin/biz/model/core"
	"github.com/ClubWeGo/douyin/kitex_server"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// UserInfoMethod .
// @router /douyin/user/ [GET]
func UserInfoMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req core.UserInfoReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	msgsucceed := "获取用户信息成功"
	msgFailed := "获取用户信息失败"

	resp := new(core.UserInfoResp)

	user, err := kitex_server.GetUser(req.UserID)
	if err != nil {
		resp.StatusCode = 1
		resp.StatusMsg = &msgFailed
		c.JSON(consts.StatusOK, resp)
		return
	}

	resp.StatusMsg = &msgsucceed
	resp.User = user
	c.JSON(consts.StatusOK, resp)
}
