// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	core "github.com/ClubWeGo/douyin/biz/router/core"
	interaction "github.com/ClubWeGo/douyin/biz/router/interaction"
	relation "github.com/ClubWeGo/douyin/biz/router/relation"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	relation.Register(r)

	interaction.Register(r)

	core.Register(r)
}
